src/vmime/charsetConverter_win.hpp

Small change, implementation had two parameters and header only had one.

Missing param in charsetConverter_win header breaking win build

---

src/vmime/headerField.cpp

Some (broken) implementation sends double-colons for certain fields, and this change makes vmime support that case.
Or maybe we should introduce a flag in the library context, settable by the library-using program, to toggle this behavior whether to be rfc-strict or not… thoughts?

Skip multiple (bogus) colons after header field name

---

src/vmime/security/cert/certificateException.cpp
src/vmime/security/cert/certificateException.hpp

Allows querying the certificate info in exception handlers catching the exception by const reference, besides other uses.

Added const overload for certificateException::getCertificate().

---

src/vmime/generationContext.cpp
src/vmime/generationContext.hpp
src/vmime/messageId.cpp

Some MUAs (at least Outlook) has problems on Content-Id being wrapped,
therefore it is desired to turn what off. By wrapping Content-Id we
mean:
Content-Id: <jira-generated-image-avatar-.................................................>
becomes
Content-Id:
<jira-generated-image-avatar-.................................................>
An option has been added to GenerationContext to force the
wrapping off (GenerationContext::setWrapMessageId(false)).
Fixes issue #154 
Signed-off-by: Bo Simonsen <b.simonsen@kopano.com>

Add option to specify if vmime should wrap (Message|Content)-Id

---

src/vmime/body.cpp
src/vmime/headerField.cpp
src/vmime/parsingContext.cpp
src/vmime/parsingContext.hpp

With no options in `parserContext` this would likely go unnoticed as the passed version would match the default generated version.  This change passes the incoming `parsingContext` to the calls to `parse` and will allow `parsingContext` to be extended with additional options to control the parsers' behavior.
This change will be a dependency #164

ensure user defined parsingContext is passed forward on calls to parse

---

src/vmime/net/imap/IMAPFolder.cpp

sizeof(byte_t*) is likely to be 4 or 8. Probably a typo.

Fixed send performance issue

---

src/vmime/encoding.hpp

This class has another "public" just five lines befores

Remove unnecesary public in vmime::enconding

---

src/vmime/mailbox.cpp

The behavior of current VMIME implementation will result in address a@b.c
with an empty name. That is because the parsing is stopped whenever a
wihtespace and a at-character is seen. We should continue the parsing to
deduce the real address (e@f.g in the example).

Handle parsing of a@b.c <e@f.g>

---

src/vmime/mailbox.cpp
tests/parser/mailboxTest.cpp

Handle "From: Your Boss <yourboss@x.com> <notyourboss@x.com>", at
least so much that the resulting displayname and address, when shown
together in a mail client, give a rough indication of the original
From line and that someone tried to use multiple addresses — or that
the MUA messed up the quoting big time.
The code is already there with `if (*p == '<')`, but a "break;" in
the '>' handling figuratively broke reaching that part.

Handle parsing of further non-conformant From lines

---

src/vmime/platforms/posix/posixHandler.cpp

Partial revert commit v0.9.2-6-g9a3d6880 (issue #160), because
invoking getaddrinfo(NULL, ... AI_CANONNAME) is illegal and never
succeeds.

Unbreak own hostname qualification on POSIX systems

---

src/vmime/charsetConverter_icu.cpp

Looks like it's not necessary, and, moreover, I'm getting this with recent ICU (64.2):
```
/usr/include/unicode/localpointer.h:67:1: error: template with C linkage
67 | template<typename T>
| ^~~~~~~~
/var/tmp/portage/dev-libs/vmime-9999/work/vmime-9999/src/vmime/charsetConverter_icu.cpp:37:1: note: ‘extern "C"’ linkage started here
37 | extern "C" {
| ^~~~~~~~~~
```
(there's also an issue about that, #218)

Avoid extern "C" blocks around ICU includes

---

src/vmime/body.cpp
tests/parser/bodyPartTest.cpp

1. The way I read the RFC is that whitespace is not allowed before the
boundary marker, only afterwards, so the checks for leading WS are
removed, and the missing check for trailing WS is added.
2. There is crap software out there that generates mails violating the prefix ban clause from RFC 2046 §5.1 ¶2, specifically CANCOM FortiMail (a gateway that intercepts e-mail and, if spam/virus is detected, instead delivers a summary mail where the recipient can then moderate these, i.e. tell the gateway to accept-deliver/hold/discard/etc.). VMIME is made to handle these malformed mails.

Boundary marker parsing: WS rules and EQ check

---

src/vmime/net/tls/gnutls/TLSSocket_GnuTLS.cpp
src/vmime/net/tls/openssl/TLSSocket_OpenSSL.cpp
src/vmime/net/tls/openssl/TLSSocket_OpenSSL.hpp

GMail in particular started requiring SNI lately. This change allows setting the SNI in the OpenSSL implementation of SSL sockets.
I cannot say I super like this approach — saving the address to `m_address` seems meh, but `createSSSLHandle()` seems to be used in contexts where the user doesn't pass the address explicitly.

Set SNI in the openssl backend

---

src/vmime/net/imap/IMAPMessagePart.cpp

This makes the `IMAPMessagePart` more omnivorous, allowing text parts having a name, and trying to parse out content-disposition for any body part type.
I've actually seen messages where attachment names fail to be obtained if either of these changes is omitted, so looks like it's useful in practice.

Body type parsing

---

src/vmime/mailbox.cpp
tests/parser/bodyTest.cpp
tests/parser/mailboxTest.cpp

When the display name contains an At sign, or anything of the sort,
libvmime would forcibly encode this to =?...?=, even if the line
is fine ASCII which only needs quoting.

Avoid force-encoding display names that fit within qcontent

---

src/vmime/exception.hpp
src/vmime/net/imap/IMAPFolder.cpp
src/vmime/net/tls/gnutls/TLSSocket_GnuTLS.cpp
src/vmime/net/tls/gnutls/TLSSocket_GnuTLS.hpp
src/vmime/net/tls/openssl/TLSSocket_OpenSSL.cpp
src/vmime/net/tls/openssl/TLSSocket_OpenSSL.hpp

net/tls: Refactored re-throwing exceptions so that the original exception class is retained. With the old code, a socket_exception was re-thrown as vmime::exception.
IMAPFolder.cpp: Fixed a use-after-free in case of an exception in close().

Exceptions handling / re-throwing fixes

---

src/vmime/net/imap/IMAPMessage.cpp

Attempts to obtain the message would trigger bad_field_value_type exception if a ReplyTo header field was present.

Fixed an ENVELOPE ReplyTo handling regression

---

src/vmime/messageParser.cpp

Default missing Content-Type to Text/Plain  as per https://tools.ietf.org/html/rfc2045#section-5.2
Such emails are routinely sent by https://en.wikipedia.org/wiki/YAM_(Yet_Another_Mailer) , but there's likely more mailers doing this.

Default missing Content-Type to Text/Plain 

---

src/vmime/net/imap/IMAPConnection.cpp
src/vmime/net/imap/IMAPConnection.hpp
src/vmime/net/imap/IMAPFolder.cpp
src/vmime/net/imap/IMAPMessage.cpp
src/vmime/net/imap/IMAPMessagePartContentHandler.cpp
src/vmime/net/imap/IMAPParser.hpp
src/vmime/net/imap/IMAPStore.cpp

Added checks to several places that either used a weak_ptr directly or via weak_ptr<Foo>.lock()->method().
Ensure disconnect() methods always close and reset the socket pointers even if the sockets are already disconnected.

Weak ptr checks + forced socket disconnections.

---

src/vmime/charsetConverter_icu.cpp
tests/parser/charsetTest.cpp

charsetFilteredOutputStream_icu::writeImpl() is accessing element in an empty buffer which is undefined behaviour.
I have added a test so that code analysis tool can detect this issue.

Prevent accessing empty buffer when using FilteredOutputStream with ICU

---

src/vmime/security/cert/X509Certificate.hpp
src/vmime/security/cert/gnutls/X509Certificate_GnuTLS.cpp
src/vmime/security/cert/openssl/X509Certificate_OpenSSL.cpp

Not the actual SHA256 digest code itself, but enough to have  GnuTLS or OpenSSL make SHA256 fingerprint digest.

Added support for digest algorithm SHA256

---

src/vmime/parsingContext.cpp
src/vmime/parsingContext.hpp

This has the potential to come into play more with #280 (parsing failure feedback).  It also comes into play with how we elected to patch for #235 (emailAddress adds domain).
This change makes the default context a thread_local item to prevent any potential issues with with multiple threads wanting to configure/adjust the behavior of the default context simultaneously.

Make default context thread_local

---

src/vmime/net/sendmail/sendmailTransport.cpp

When the ``sender`` function argument is the empty object, vmime would still attempt to use it at ``sender.getEmail().generate()``, but that produces just ``@``. As sendmail is called with ``-f @``, this shows up in postfix's logs as ``<""@>``.

Avoid generating illegal Envelope-From with sendmail:// transport

---

src/vmime/utility/url.cpp
tests/utility/urlTest.cpp

`hostPart[len]` is pointing to `]`, but we need to check the char after that.
Fixes: v0.9.2-187-g874a1d8c

url: repair off-by-one bug in extractHost

---

src/vmime/utility/url.cpp
tests/utility/urlTest.cpp

Observed:
1. `http://host/` leads to path=""
2. `http://host/a` leads to path="/a"
That can't be right. Either case 1 must produce path="/", or case 2 must produce path="a".
RFC says `/` is not part of the path, so we'll go for path="a".

url: strip leading slash from url-path

---

tests/parser/textTest.cpp

Switch out the byte sequence by one that is simiarly random, but one which happens to decode as valid UTF-8, such that the expected and actual strings are shown with reasonable characters on a terminal.

tests: switch a byte sequence in textTest

---

src/vmime/text.cpp
src/vmime/word.cpp
tests/parser/mailboxTest.cpp
tests/parser/textTest.cpp

```
mailbox(text("Test München West", charsets::UTF_8), "a@b.de").generate();
```
produces
```
=?us-ascii?Q?Test_?= =?utf-8?Q?M=C3=BCnchen?= =?us-ascii?Q?West?= <test@example.com>
```
The first space between ``Test`` and ``München`` is encoded as an underscore along with the first word: ``Test_``. The second space between ``München`` and ``West`` is encoded with neither of the two words and thus lost. Decoding the text results in ``Test MünchenWest`` instead of ``Test München West``.
This is caused by how ``vmime::text::createFromString()`` handles transitions between 7-bit and 8-bit words: If an 8-bit word follows a 7-bit word, a space is appended to the previous word. The opposite case of a 7-bit word following an 8-bit word *misses* this behaviour.
When one fixes this problem, a …

vmime: prevent loss of a space during text::createFromString

---

src/vmime/emailAddress.cpp
src/vmime/path.cpp
tests/parser/textTest.cpp

Partially revert v0.9.2-183-g9b65b4de.
As per RFC 5322 §3.4.1, an email address must always have a @.
As per RFC 5321 §4.1.2, a path is similar to an email address (always
@), with "" (<>) being the only other special value.
Fixes #294, #301.

Fix a test failure in pathTest::testGenerate

---

.github/workflows/build.yml

The id `ubuntu-latest` was deprecated a while ago.

gh: update GitHub workflow for new Ubuntu image
